title: "Aysun Mutlu"
email: "aysun.mutlu@mail.mcgill.ca"
description: >-
  A personal and professional space for my research, projects, and ideas.
baseurl: ""
url: "https://aysunmutlu.com"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: null
plugins:
  - jekyll-include-cache

header_pages:
  - about.md
  - research.md
  - projects.md
  - contact.md

author:
  name: "Aysun Mutlu"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD in Operations Management · Data Scientist · Explorer of systems, stories, and human behavior"
  location: "Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/aysun-mutlu"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/1AysunMutlu"