title: "Aysun Mutlu"
description: "Data Scientist | PhD in Operations Management"
baseurl: ""
url: "https://aysunmutlu.com"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Aysun Mutlu"
  avatar: "/assets/images/profile.jpg"
  bio: "Customer Behavior • Optimization • Data Science"
  location: "Canada"

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

permalink: /:title/
