title: "Aysun Mutlu"
email: "aysun.mutlu@mail.mcgill.ca"
description: >-
  A personal and professional space for my research, projects, and ideas.
baseurl: "" # leave empty for root
url: "https://aysunmutlu.com"

# Theme and plugins
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: null
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default

# Add custom CSS
sass:
  style: compressed
  load_paths:
    - _sass
    - assets/css

# Custom includes
include:
  - _pages
  - assets/css

navigation:
  enabled: true
  style: links

# Author information
author:
  name: "Aysun Mutlu"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD in Operations Management · Data Scientist · Explorer of systems, stories, and human behavior"
  location: "Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/aysun-mutlu"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/1AysunMutlu"

# Social sharing
twitter_username: ""
github_username: "1AysunMutlu"

# SEO and sitemap
minimal_mistakes_skin: "default"
search: true
breadcrumbs: true
timezone: America/Toronto

# Optional: Google Analytics or GoatCounter (visitor stats)
# goat_counter: "aysunmutlu"

defaults:
  -
    scope:
      path: ""
    values:
      custom_css: assets/css/custom.css

# Footer
footer:
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/aysun-mutlu"
    - label: "GitHub"
      url: "https://github.com/1AysunMutlu"