title: "Aysun Mutlu"
email: "aysun.mutlu@mail.mcgill.ca"
description: >-
  A personal and professional space for my research, projects, and ideas.
baseurl: "" # leave empty for root
url: "https://aysunmutlu.com"

# Theme and plugins
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Navigation tabs
header_pages:
  - about.md
  - research.md
  - projects.md
  - contact.md

# Author information
author:
  name: "Aysun Mutlu"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD in Operations Management · Data Scientist · Explorer of systems, stories, and human behavior"
  location: "Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/aysun-mutlu"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/1AysunMutlu"

# Social sharing
twitter_username: ""
github_username: "1AysunMutlu"

# SEO and sitemap
minimal_mistakes_skin: "default"
search: true
breadcrumbs: true
timezone: America/Toronto

# Optional: Google Analytics or GoatCounter (visitor stats)
# goat_counter: "aysunmutlu"

# Footer
footer:
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/aysun-mutlu"
    - label: "GitHub"
      url: "https://github.com/1AysunMutlu"